apiVersion: v1
kind: Pod
metadata: 
  name: "pod1"
  labels: 
    region: IN
spec: 
  volumes: 
  - name: s1
    persistentVolumeClaim: 
       claimName: mycreationofpvc
  containers: 
  - name: "myc1"
    image: "vimal13/apache-webserver-php"
    volumeMounts: 
    - mountPath: /var/www/data
      name: s1


    