apiVersion: v1
kind: ReplicationController
metadata:
  name: rc1
spec:
  replicas: 1
  selector:
    dc: US
  template:
    metadata: 
      name: "mypod5"
      labels:
        dc: US
        team: team1
    spec:
      containers:
      - name: "myc2"
        image: "vimal13/apache-webserver-php"









