apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs1
spec:
  replicas: 2
  selector:
   matchExpressions:
   - { key: dc, operator: In, values: [US] }
   - { key: team, operator: In, values: [team1] }
  template:
    metadata: 
      name: "mypod5"
      labels:
        dc: US
        team: team1
    spec:
      containers:
      - name: "myc2"
        image: "vimal13/apache-webserver-php"









